id: app
title: New Compliance App
type: project
version: 0.1.0
icon: app.png
catalog:
  category: Preview
  vendor: GovReady
  vendor_url: ~
  status: stub
  version: 0.1.0
  source_url: ~
  description:
    short: |
      Short description.
introduction:
  format: markdown
  template: |
    Use this app to achieve compliance.
questions:
  - id: example
    title: Example Module
    type: module
    module-id: example
