# This file is a template, and might need editing before it works on your project.
include:
  - template: Jobs/SAST-IaC.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
