# Generated by Django 2.2.12 on 2020-04-21 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0007_auto_20200420_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='elements',
        ),
        migrations.AddField(
            model_name='statement',
            name='described_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_describing', to='controls.Element'),
        ),
        migrations.AddField(
            model_name='statement',
            name='referenced_elements',
            field=models.ManyToManyField(blank=True, related_name='statement_referencing', to='controls.Element'),
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisma_id', models.CharField(help_text='The FISMA Id of the system', max_length=40)),
                ('root_element', models.ForeignKey(help_text='The Element that is this System. Element must be type [Application, General Support System]', on_delete=django.db.models.deletion.CASCADE, related_name='system', to='controls.Element')),
            ],
        ),
        migrations.CreateModel(
            name='ElementControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oscal_ctl_id', models.CharField(blank=True, help_text='OSCAL formatted Control ID (e.g., au-2.3)', max_length=20, null=True)),
                ('oscal_catalog_id', models.CharField(blank=True, help_text="OSCAL formatted Catolog ID (e.g., 'uuid-26a2a133-f395-432c-b2ad-77d23a23ca4e')", max_length=80, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('element', models.ForeignKey(help_text='The Element (e.g., System, Component, Host) to which controls are associated.', on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='controls.Element')),
            ],
            options={
                'unique_together': {('element', 'oscal_ctl_id', 'oscal_catalog_id')},
            },
        ),
    ]
