# Generated by Django 2.2.12 on 2020-04-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0009_auto_20200421_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='fisma_id',
            field=models.CharField(blank=True, help_text='The FISMA Id of the system', max_length=40, null=True),
        ),
    ]
