# Generated by Django 2.2.12 on 2020-05-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0013_auto_20200430_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statement',
            options={'permissions': [('can_grant_smt_owner_permission', 'Grant a user statement owner permission')]},
        ),
    ]
