# Generated by Django 3.0.7 on 2020-08-04 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0024_auto_20200804_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poam',
            name='statement',
            field=models.ForeignKey(blank=True, help_text='The Poam details for this statement. Statement must be type Poam', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poam', to='controls.Statement'),
        ),
    ]
