# Generated by Django 3.0.7 on 2020-08-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0026_auto_20200804_0239_squashed_0027_auto_20200804_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poam',
            name='poam_id',
            field=models.IntegerField(blank=True, help_text='The sequential ID for the information system.', null=True),
        ),
        migrations.AlterField(
            model_name='poam',
            name='statement',
            field=models.OneToOneField(blank=True, help_text='The Poam details for this statement. Statement must be type Poam.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poam', to='controls.Statement'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='consumer_element',
            field=models.ForeignKey(blank=True, help_text='The element the statement is about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements_consumed', to='controls.Element'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='producer_element',
            field=models.ForeignKey(blank=True, help_text='The element producing this statement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements_produced', to='controls.Element'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='remarks',
            field=models.TextField(blank=True, help_text='Remarks about the statement.', null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='sid_class',
            field=models.CharField(blank=True, help_text="Statement identifier 'class' such as 'NIST_SP-800-53_rev4' or other OSCAL catalog name Control ID.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement_type',
            field=models.CharField(blank=True, help_text='Statement type.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.CharField(blank=True, help_text='The status of the statement.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='version',
            field=models.CharField(blank=True, help_text='Optional version number.', max_length=20, null=True),
        ),
    ]
