# Generated by Django 3.0.7 on 2020-09-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0027_auto_20200804_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='prototype',
            field=models.ForeignKey(blank=True, help_text='Prototype statement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='controls.Statement'),
        ),
    ]
