# Generated by Django 3.0.7 on 2020-09-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0028_poam_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poam',
            name='group',
        ),
        migrations.AddField(
            model_name='poam',
            name='poam_group',
            field=models.CharField(blank=True, help_text='The name of the POA&M group, if any, this control belongs to.', max_length=50, null=True),
        ),
    ]
