# Generated by Django 3.0.7 on 2020-09-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0029_auto_20200909_1812'),
        ('controls', '0028_elementcontrol_uuid'),
    ]

    operations = [
    ]
