# Generated by Django 3.0.7 on 2020-09-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0029_auto_20200909_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
