# Generated by Django 3.0.7 on 2020-10-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0030_issuetracker'),
        ('controls', '0030_merge_20200920_1243'),
    ]

    operations = [
    ]
