# Generated by Django 3.0.7 on 2020-11-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0031_statement_prototype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='prototype',
        ),
    ]
