# Generated by Django 3.0.7 on 2020-11-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0032_auto_20201113_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(blank=True, help_text='Component type', max_length=150, null=True),
        ),
    ]
