# Generated by Django 3.0.11 on 2021-01-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0037_deployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='name',
            field=models.CharField(help_text='Name of the deployment', max_length=250),
        ),
    ]
