# Generated by Django 3.0.11 on 2021-01-17 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controls', '0039_auto_20210116_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='inventory_items',
            field=jsonfield.fields.JSONField(blank=True, help_text='JSON object representing the inventory items in a deployment.', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalDeployment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the deployment', max_length=250)),
                ('description', models.CharField(help_text='Brief description of the deployment', max_length=255)),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='A UUID (a unique identifier) for the deployment.')),
                ('inventory_items', jsonfield.fields.JSONField(blank=True, help_text='JSON object representing the inventory items in a deployment.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(blank=True, db_constraint=False, help_text='The system associated with the deployment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.System')),
            ],
            options={
                'verbose_name': 'historical deployment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
