# Generated by Django 3.0.11 on 2021-01-28 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controls', '0040_auto_20210117_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAssessmentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the system assessment result', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='A UUID (a unique identifier) for the system assessment result.')),
                ('assessment_results', jsonfield.fields.JSONField(blank=True, help_text='JSON object representing the system assessment results associated with a deployment.', null=True)),
                ('deployment', models.ForeignKey(blank=True, help_text='The deployment associated with the assessment result.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_results', to='controls.Deployment')),
                ('system', models.ForeignKey(blank=True, help_text='The system associated with the system assessment result', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_assessment_result', to='controls.System')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSystemAssessmentResult',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the system assessment result', max_length=250)),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='A UUID (a unique identifier) for the system assessment result.')),
                ('assessment_results', jsonfield.fields.JSONField(blank=True, help_text='JSON object representing the system assessment results associated with a deployment.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deployment', models.ForeignKey(blank=True, db_constraint=False, help_text='The deployment associated with the assessment result.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.Deployment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(blank=True, db_constraint=False, help_text='The system associated with the system assessment result', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.System')),
            ],
            options={
                'verbose_name': 'historical system assessment result',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
