# Generated by Django 3.0.11 on 2021-02-03 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0040_auto_20210117_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='consumer_element',
            field=models.ForeignKey(blank=True, help_text='The element the statement is about.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements_consumed', to='controls.Element'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='producer_element',
            field=models.ForeignKey(blank=True, help_text='The element producing this statement.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements_produced', to='controls.Element'),
        ),
    ]
