# Generated by Django 3.0.11 on 2021-01-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0041_historicalsystemassessmentresult_systemassessmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemassessmentresult',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description of the system assessment result', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemassessmentresult',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description of the system assessment result', max_length=255, null=True),
        ),
    ]
