# Generated by Django 3.0.11 on 2021-02-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0041_auto_20210203_0937'),
        ('controls', '0042_auto_20210129_0416'),
    ]

    operations = [
    ]
