# Generated by Django 3.0.11 on 2021-02-07 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0043_merge_20210203_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatement',
            name='delegate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Delegate statement', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.Statement'),
        ),
        migrations.AddField(
            model_name='statement',
            name='delegate',
            field=models.ForeignKey(blank=True, help_text='Delegate statement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegators', to='controls.Statement'),
        ),
    ]
