# Generated by Django 3.1.7 on 2021-03-18 09:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0045_auto_20210228_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Common name or acronym of the role', max_length=250, unique=True)),
                ('description', models.CharField(help_text='Brief description of the Element', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles assigned to the Element', related_name='elements', to='controls.ElementRole'),
        ),
    ]
