# Generated by Django 3.1.8 on 2021-04-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0046_element_tags'),
        ('controls', '0046_auto_20210318_0915'),
    ]

    operations = [
    ]
