# Generated by Django 3.2 on 2021-05-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0049_auto_20210518_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='component_state',
            field=models.CharField(blank=True, choices=[('UNDER_DEVELOPMENT', 'under-development'), ('OPERATIONAL', 'operational'), ('DISPOSITION', 'disposition'), ('OTHER', 'other')], default='operational', help_text='Component State.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='component_type',
            field=models.CharField(blank=True, choices=[('HARDWARE', 'hardware'), ('SOFTWARE', 'software'), ('SERVICE', 'service'), ('POLICY', 'policy'), ('PROCESS', 'process'), ('PROCEDURE', 'procedure')], default='software', help_text='Component Type.', max_length=150, null=True),
        ),
    ]
