# Generated by Django 3.1.8 on 2021-06-29 23:28
# Updated by Greg

from django.db import migrations
from django.apps import apps
from controls.enums.statements import StatementTypeEnum


def update_statement_type_to_enum_name(apps, schema_editor):
    """Update the statement_type values to use enum 'name' instead of enum 'value'"""

    apps.get_model("controls", "Statement")\
        .objects\
        .filter(statement_type=StatementTypeEnum.CONTROL_IMPLEMENTATION.value)\
        .update(statement_type=StatementTypeEnum.CONTROL_IMPLEMENTATION.name)

    apps.get_model("controls", "Statement")\
        .objects\
        .filter(statement_type=StatementTypeEnum.CONTROL_IMPLEMENTATION_LEGACY.value)\
        .update(statement_type=StatementTypeEnum.CONTROL_IMPLEMENTATION_LEGACY.name)

    apps.get_model("controls", "Statement")\
        .objects\
        .filter(statement_type=StatementTypeEnum.CONTROL_IMPLEMENTATION_PROTOTYPE.value)\
        .update(statement_type=StatementTypeEnum.CONTROL_IMPLEMENTATION_PROTOTYPE.name)

    apps.get_model("controls", "Statement")\
        .objects\
        .filter(statement_type=StatementTypeEnum.ASSESSMENT_RESULT.value)\
        .update(statement_type=StatementTypeEnum.ASSESSMENT_RESULT.name)

    apps.get_model("controls", "Statement")\
        .objects\
        .filter(statement_type=StatementTypeEnum.POAM.value)\
        .update(statement_type=StatementTypeEnum.POAM.name)

    apps.get_model("controls", "Statement")\
        .objects\
        .filter(statement_type=StatementTypeEnum.SECURITY_SENSITIVITY_LEVEL.value)\
        .update(statement_type=StatementTypeEnum.SECURITY_SENSITIVITY_LEVEL.name)

    apps.get_model("controls", "Statement")\
        .objects\
        .filter(statement_type=StatementTypeEnum.SECURITY_IMPACT_LEVEL.value)\
        .update(statement_type=StatementTypeEnum.SECURITY_IMPACT_LEVEL.name)

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('controls', '0051_auto_20210520_1213'),
    ]

    operations = [
         migrations.RunPython(update_statement_type_to_enum_name)
    ]
