# Generated by Django 3.2.3 on 2021-07-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0052_auto_20210521_1422'),
        ('controls', '0053_auto_20210701_1133'),
    ]

    operations = [
    ]
