# Generated by Django 3.2.5 on 2021-08-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0061_statementremote'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatement',
            name='change_log',
            field=models.JSONField(blank=True, help_text='JSON object representing changes to the statement', null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='change_log',
            field=models.JSONField(blank=True, help_text='JSON object representing changes to the statement', null=True),
        ),
    ]
