# Generated by Django 3.2.5 on 2021-09-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0062_statementremote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inheritance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('responsibility', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
