# Generated by Django 3.2.5 on 2021-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0062_statementremote'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatement',
            name='oscal_data',
            field=models.JSONField(blank=True, help_text='JSON object representing additional OSCAL props, links, etc.', null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='oscal_data',
            field=models.JSONField(blank=True, help_text='JSON object representing additional OSCAL props, links, etc.', null=True),
        ),
    ]
