# Generated by Django 3.2.5 on 2021-09-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0062_statementremote'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementcontrol',
            name='status',
            field=models.IntegerField(choices=[(2, 'Open'), (3, 'Ready for Review'), (4, 'Needs Review'), (5, 'Accepted')], default=2),
        ),
    ]
