# Generated by Django 3.2.5 on 2021-10-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0049_auto_20210423_1555'),
        ('controls', '0062_statementremote'),
    ]

    operations = [
    ]
