# Generated by Django 3.2.5 on 2021-10-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0063_merge_0049_auto_20210423_1555_0062_statementremote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncontrolprovider',
            name='created',
        ),
        migrations.RemoveField(
            model_name='commoncontrolprovider',
            name='updated',
        ),
        migrations.AlterField(
            model_name='element',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstatement',
            name='updated',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='statement',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
