# Generated by Django 3.2.12 on 2022-03-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0066_element_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
