# Generated by Django 3.2.12 on 2022-03-25 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0053_party_role'),
        ('controls', '0067_alter_element_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='requestRequired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='responsible_parties',
            field=models.ManyToManyField(related_name='element', to='siteapp.Party'),
        ),
        migrations.AddField(
            model_name='element',
            name='responsible_roles',
            field=models.ManyToManyField(related_name='element', to='siteapp.Role'),
        ),
    ]
