# Generated by Django 3.2.12 on 2022-03-25 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0053_party_role'),
        ('controls', '0067_alter_element_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='requestRequired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='responsible_parties',
            field=models.ManyToManyField(related_name='element', to='siteapp.Party'),
        ),
        migrations.AddField(
            model_name='element',
            name='responsible_role',
            field=models.ManyToManyField(related_name='element', to='siteapp.Role'),
        ),
        migrations.CreateModel(
            name='ElementPointOfContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='Common name or acronym of the element', max_length=250, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('elements', models.ManyToManyField(to='controls.Element')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
