# Generated by Django 3.2.12 on 2022-03-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0053_auto_20220326_1416'),
        ('controls', '0067_alter_element_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='hidden',
            field=models.BooleanField(default=True, help_text='Component is hidden.'),
        ),
        migrations.AddField(
            model_name='element',
            name='require_approval',
            field=models.BooleanField(blank=True, default=False, help_text='Component requires approval to use.', null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='responsible_roles',
            field=models.ManyToManyField(related_name='element', to='siteapp.Role'),
        ),
        migrations.AlterField(
            model_name='element',
            name='private',
            field=models.BooleanField(default=True, help_text='Component is private.'),
        ),
    ]
