# Generated by Django 3.2.12 on 2022-03-05 18:36

from django.db import migrations, models

def system_info_schema(apps, schema_editor):
    SystemSettings = apps.get_model('system_settings', 'SystemSettings')
    system_info_schema = SystemSettings.objects.create(setting='system_info_schema')
    system_info_schema.details = dict()
    system_info_schema.save()

class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0067_alter_element_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='info',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object representing additional system information'),
        ),
        migrations.RunPython(system_info_schema, migrations.RunPython.noop)
    ]
