# Generated by Django 3.2.12 on 2022-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0068_auto_20220329_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='require_approval',
            field=models.BooleanField(default=False, help_text='Component requires approval to use.'),
        ),
    ]
