# Generated by Django 3.2.13 on 2022-04-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0062_remove_proposal_system'),
        ('controls', '0070_auto_20220418_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='proposals',
            field=models.ManyToManyField(related_name='system', to='siteapp.Proposal'),
        ),
    ]
