# Generated by Django 3.2.13 on 2022-05-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0071_system_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='info',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object representing additional system information'),
        ),
    ]
