# Generated by Django 3.2.13 on 2022-06-21 11:14

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0066_alter_project_tags'),
        ('controls', '0074_auto_20220614_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('event_type', models.CharField(help_text='Event type', max_length=12)),
                ('description', models.CharField(help_text='Brief description of the event', max_length=255)),
                ('info', models.JSONField(blank=True, default=dict, help_text='JSON object detailed event information')),
                ('system', auto_prefetch.ForeignKey(blank=True, help_text='Events related to the system', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='controls.system')),
                ('tags', models.ManyToManyField(blank=True, related_name='systemevent', to='siteapp.Tag')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
