# Generated by Django 3.2.14 on 2022-07-12 14:24

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0075_systemevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='import_record',
            field=auto_prefetch.ForeignKey(blank=True, help_text='The Import Record which created this System.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_record_systems', to='controls.importrecord'),
        ),
    ]
