# Generated by Django 3.2.14 on 2022-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0077_historicalpoam_historicalsystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstatement',
            name='import_record',
        ),
        migrations.RemoveField(
            model_name='historicalsystem',
            name='import_record',
        ),
        migrations.AddField(
            model_name='importrecord',
            name='comment',
            field=models.TextField(blank=True, help_text='Comment for this import record', null=True),
        ),
        migrations.RemoveField(
            model_name='statement',
            name='import_record',
        ),
        migrations.AddField(
            model_name='statement',
            name='import_record',
            field=models.ManyToManyField(blank=True, help_text='The Import Record which created this Statement.', null=True, related_name='import_record_statements', to='controls.ImportRecord'),
        ),
        migrations.RemoveField(
            model_name='system',
            name='import_record',
        ),
        migrations.AddField(
            model_name='system',
            name='import_record',
            field=models.ManyToManyField(blank=True, help_text='The Import Record which created this System.', null=True, related_name='import_record_systems', to='controls.ImportRecord'),
        ),
    ]
