# Generated by Django 3.2.14 on 2022-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0078_auto_20220719_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='poam',
            name='import_record',
            field=models.ManyToManyField(blank=True, help_text='The Import Record which created this Poam.', related_name='import_record_poam', to='controls.ImportRecord'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='import_record',
            field=models.ManyToManyField(blank=True, help_text='The Import Record which created this Statement.', related_name='import_record_statements', to='controls.ImportRecord'),
        ),
        migrations.AlterField(
            model_name='system',
            name='import_record',
            field=models.ManyToManyField(blank=True, help_text='The Import Record which created this System.', related_name='import_record_systems', to='controls.ImportRecord'),
        ),
    ]
