# Generated by Django 3.2.14 on 2022-07-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0079_auto_20220719_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpoam',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Additional fields'),
        ),
        migrations.AddField(
            model_name='historicalsystem',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Additional fields'),
        ),
        migrations.AddField(
            model_name='poam',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Additional fields'),
        ),
        migrations.AddField(
            model_name='system',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Additional fields'),
        ),
    ]
