# Generated by Django 3.2.19 on 2023-06-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0080_auto_20220725_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementcommoncontrol',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='elementcontrol',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='statement',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['producer_element__name', 'sid'], 'permissions': [('can_grant_smt_owner_permission', 'Grant a user statement owner permission')]},
        ),
    ]
