# Generated by Django 3.2.15 on 2022-09-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0080_auto_20220725_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='purpose',
            field=models.TextField(blank=True, default='', help_text='A summary of the technological or business purpose of the component.'),
        ),
    ]
