# Generated by Django 3.2.16 on 2022-10-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0083_auto_20221025_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentid',
            options={},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systemtask',
            options={},
        ),
        migrations.AlterModelManagers(
            name='documentid',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='link',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='prop',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='systemtask',
            managers=[
            ],
        ),
    ]
