# Generated by Django 3.2.16 on 2022-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0072_auto_20221025_2017'),
        ('controls', '0085_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='A location, with associated metadata that can be referenced.', related_name='locations', to='siteapp.Location'),
        ),
    ]
