# Generated by Django 3.2.16 on 2022-10-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0087_auto_20221031_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='lastModified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
