# Generated by Django 3.2.16 on 2022-10-31 20:46

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0090_auto_20221031_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='base64',
            field=models.ForeignKey(blank=True, help_text='The Base64 alphabet in RFC 2045 - aligned with XSD.', null=True, on_delete=django.db.models.deletion.CASCADE, to='controls.base64'),
        ),
        migrations.AddField(
            model_name='resource',
            name='citation',
            field=auto_prefetch.ForeignKey(blank=True, help_text='A citation consisting of end note text and optional structured bibliographic data.', null=True, on_delete=django.db.models.deletion.CASCADE, to='controls.citation'),
        ),
        migrations.AddField(
            model_name='resource',
            name='rlinks',
            field=models.ManyToManyField(blank=True, help_text='A pointer to an external resource with an optional hash for verification and change detection.', null=True, related_name='resource', to='controls.RLink'),
        ),
    ]
