# Generated by Django 3.2.16 on 2022-11-01 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0072_auto_20221025_2017'),
        ('controls', '0091_auto_20221031_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='A machine-oriented, globally unique identifier with cross-instance scope that can be used to reference this defined resource elsewhere in this or other OSCAL instances.')),
                ('description', models.TextField(blank=True, help_text='Description of this Role.', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional commentary on the containing object.', null=True)),
                ('implemented_components', models.ManyToManyField(blank=True, help_text='The set of components that are implemented in a given system inventory item.', null=True, related_name='inventory_item', to='controls.Element')),
                ('links', models.ManyToManyField(blank=True, related_name='inventoryitem', to='controls.Link')),
                ('props', models.ManyToManyField(blank=True, related_name='inventoryitem', to='controls.Prop')),
                ('responsible_parties', models.ManyToManyField(blank=True, help_text='A reference to a set of organizations or persons that have responsibility for performing a referenced role in the context of the containing object.', null=True, related_name='inventory_item', to='siteapp.Party')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
