# Generated by Django 3.2.16 on 2022-11-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0072_auto_20221025_2017'),
        ('controls', '0092_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='implemented_components',
            field=models.ManyToManyField(blank=True, help_text='The set of components that are implemented in a given system inventory item.', related_name='inventory_item', to='controls.Element'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='responsible_parties',
            field=models.ManyToManyField(blank=True, help_text='A reference to a set of organizations or persons that have responsibility for performing a referenced role in the context of the containing object.', related_name='inventory_item', to='siteapp.Party'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='A document identifier qualified by an identifier scheme.', related_name='resource', to='controls.DocumentId'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rlinks',
            field=models.ManyToManyField(blank=True, help_text='A pointer to an external resource with an optional hash for verification and change detection.', related_name='resource', to='controls.RLink'),
        ),
    ]
