# Generated by Django 2.2.4 on 2019-10-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(help_text='The unique identifier of an installed Agent on a Host Instance.', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='AgentService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this endpoint/host Agent Service .', max_length=255, unique=True)),
                ('api_user', models.CharField(help_text="The user/login identify for accessing Agent Service's API.", max_length=255)),
                ('api_pw', models.CharField(help_text="The user/login password for accessing Agent Service's API.", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HostInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this Host Instance (e.g., workload/endpoint/server).', max_length=255, unique=True)),
                ('host_type', models.CharField(help_text='A categorization of the host.', max_length=24)),
                ('os', models.CharField(help_text='The Operating System running on the Host Instance.', max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='SystemInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this IT System Instance.', max_length=255, unique=True)),
                ('sdlc_stage', models.CharField(help_text='The stage of the System Development Life Cycle System is in.', max_length=24)),
            ],
        ),
    ]
