# Generated by Django 2.2.4 on 2019-10-21 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0002_auto_20191021_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_service',
            field=models.ForeignKey(default=1, help_text='The AgentService to which this Agent belonts.', on_delete='CASCADE', related_name='agent', to='itsystems.AgentService'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='host_instance',
            field=models.ForeignKey(blank=True, help_text='The HostInstance on which the Agent is installed and monitoring.', null=True, on_delete='models.SET_NULL', related_name='agent', to='itsystems.HostInstance'),
        ),
        migrations.AddField(
            model_name='hostinstance',
            name='system_instance',
            field=models.ForeignKey(blank=True, help_text='The SystemInstance to which this HostInstance belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_instance', to='itsystems.SystemInstance'),
        ),
    ]
