# Generated by Django 2.2.4 on 2019-10-21 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0004_auto_20191021_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinstance',
            name='system_instance',
            field=models.ForeignKey(blank=True, help_text='The SystemInstance to which this HostInstance belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostinstances', to='itsystems.SystemInstance'),
        ),
    ]
