# Generated by Django 2.2.4 on 2019-10-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0006_auto_20191021_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Vendor.', max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name of a usable component.', max_length=200)),
                ('version', models.CharField(blank=True, help_text='The current version number for this component.', max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('vendor', models.ForeignKey(help_text='The vendor who supports or sells this component.', on_delete='CASCADE', related_name='components', to='itsystems.Vendor')),
            ],
        ),
    ]
