# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-30 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0007_auto_20160730_1221'),
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='organization',
            field=models.ForeignKey(default=1, help_text='The Organization that this Discussion belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='siteapp.Organization'),
            preserve_default=False,
        ),
    ]
