# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_auto_20161124_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='discussion',
        ),
        migrations.AddField(
            model_name='comment',
            name='draft',
            field=models.BooleanField(default=False, help_text='Set to true if the comment is a draft.'),
        ),
    ]
