# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_auto_20170408_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='guests',
            field=models.ManyToManyField(blank=True, help_text="Additional Users who are participating in this chat, besides those that are implicit discussion members via the Discussion's attached_to object.", related_name='guest_in_discussions', to=settings.AUTH_USER_MODEL),
        ),
    ]
