# Generated by Django 2.0.2 on 2018-02-12 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_auto_20170613_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(help_text='The user uploading this attachment.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='The user making a comment.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
