# Generated by Django 3.0.7 on 2020-11-03 13:30

import discussion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_auto_20180212_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(help_text='The attached file.', upload_to='discussion/attachments', validators=[discussion.validators.validate_file_extension]),
        ),
    ]
