# Generated by Django 3.2.5 on 2021-10-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0008_auto_20210423_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
