# Generated by Django 3.2.12 on 2022-03-08 10:00

import auto_prefetch
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import jsonfield.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='Endpoint name in lowercase', max_length=250)),
                ('description', models.TextField(blank=True, default='', help_text='Brief description of the Integration', null=True)),
                ('config', jsonfield.fields.JSONField(blank=True, default=dict, help_text='Integration configuration', null=True)),
                ('config_schema', jsonfield.fields.JSONField(blank=True, default=dict, help_text='Integration schema', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalEndpoint',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('endpoint_path', models.CharField(blank=True, help_text='Path to the Endpoint', max_length=250, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Brief description of the endpoint', null=True)),
                ('element_type', models.CharField(blank=True, help_text='Component type', max_length=150, null=True)),
                ('data', jsonfield.fields.JSONField(blank=True, default=dict, help_text='JSON object representing the API results.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('integration', auto_prefetch.ForeignKey(blank=True, db_constraint=False, help_text="Endpoint's Integration", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'historical endpoint',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('endpoint_path', models.CharField(blank=True, help_text='Path to the Endpoint', max_length=250, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Brief description of the endpoint', null=True)),
                ('element_type', models.CharField(blank=True, help_text='Component type', max_length=150, null=True)),
                ('data', jsonfield.fields.JSONField(blank=True, default=dict, help_text='JSON object representing the API results.', null=True)),
                ('integration', auto_prefetch.ForeignKey(help_text="Endpoint's Integration", on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='integrations.integration')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
