# Generated by Django 3.2.13 on 2022-05-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalendpoint',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical endpoint', 'verbose_name_plural': 'historical endpoints'},
        ),
        migrations.AlterField(
            model_name='historicalendpoint',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
