version: "3"
networks:
  q_network:
    driver: bridge


services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210422
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=60
    ports:
      - "6900:5900"
    networks:
      - q_network
