version: "3"
networks:
  q_network:
    driver: bridge


services:
  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-prerelease-20210422
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - q_network