# Generated by Django 3.2.14 on 2022-08-14 18:57

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflowrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowimage',
            name='workflowrecipe',
            field=auto_prefetch.ForeignKey(help_text='WorkflowRecipe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflowimages', to='workflow.workflowrecipe'),
        ),
    ]
