# Generated by Django 3.2.14 on 2022-08-12 01:58

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0080_auto_20220725_1728'),
        ('workflow', '0002_auto_20220812_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstance',
            name='system',
            field=auto_prefetch.ForeignKey(blank=True, help_text='System', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflowinstances', to='controls.system'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='workflowinstanceset',
            field=auto_prefetch.ForeignKey(blank=True, help_text='System', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflowinstances', to='workflow.workflowinstanceset'),
        ),
    ]
