# Generated by Django 3.2.14 on 2022-08-12 02:00

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20220812_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstance',
            name='workflowinstanceset',
            field=auto_prefetch.ForeignKey(blank=True, help_text='System', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflowinstances', to='workflow.workflowinstanceset'),
        ),
    ]
