# Generated by Django 2.0.13 on 2019-08-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
