# Generated by Django 2.0.13 on 2019-08-08 19:47

from django.db import migrations


def hide_registration(apps, schema_editor):
    SystemSettings = apps.get_model('system_settings', 'SystemSettings')
    hide_registration = SystemSettings.objects.create(setting='hide_registration')
    hide_registration.save()

class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [migrations.RunPython(hide_registration, migrations.RunPython.noop)]
