# Generated by Django 3.0.7 on 2020-06-23 15:39

from django.db import migrations


def enable_experimental_opencontrol(apps, schema_editor):
    SystemSettings = apps.get_model('system_settings', 'SystemSettings')
    enable_experimental_opencontrol = SystemSettings.objects.create(setting='enable_experimental_opencontrol')
    enable_experimental_opencontrol.save()

def enable_experimental_oscal(apps, schema_editor):
    SystemSettings = apps.get_model('system_settings', 'SystemSettings')
    enable_experimental_oscal = SystemSettings.objects.create(setting='enable_experimental_oscal')
    enable_experimental_oscal.save()

class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(enable_experimental_opencontrol, migrations.RunPython.noop),
        migrations.RunPython(enable_experimental_oscal, migrations.RunPython.noop),
    ]
