# Generated by Django 3.0.7 on 2020-06-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_auto_20200623_1539'),
        ('system_settings', '0002_auto_20190808_1947'),
    ]

    operations = [
    ]
