# Generated by Django 3.0.7 on 2020-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_merge_20200623_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_email', models.EmailField(blank=True, help_text='Support email address', max_length=254, null=True)),
                ('support_phone', models.CharField(blank=True, help_text='Support phone number', max_length=24, null=True)),
                ('support_text', models.TextField(blank=True, help_text='Support desription at top of page', null=True)),
            ],
        ),
    ]
