# Generated by Django 3.1.7 on 2021-03-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0005_delete_20210203_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'fouo'), (2, 'confidential'), (3, 'secret'), (4, 'top secret')], default=1)),
            ],
        ),
    ]
