# Generated by Django 3.0.7 on 2020-08-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0005_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='support_url',
            field=models.URLField(blank=True, help_text='Support url', null=True),
        ),
    ]
