# Generated by Django 3.1.7 on 2021-03-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0006_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='status',
            field=models.CharField(choices=[('NONE', 'none'), ('FOUO', 'fouo'), ('CONFIDENTIAL', 'confidential'), ('SECRET', 'secret'), ('TOPSECRET', 'top secret')], default='NONE', max_length=16),
        ),
    ]
