# Generated by Django 3.1.7 on 2021-03-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0008_auto_20210325_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=128)),
            ],
        ),
    ]
