# Generated by Django 3.2.4 on 2021-07-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0009_sitename'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='details',
            field=models.JSONField(blank=True, help_text='Value objects of System Setting in JSON', null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='setting',
            field=models.CharField(help_text='Name of System Setting', max_length=200, unique=True),
        ),
    ]
