# Generated by Django 3.1.8 on 2021-04-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0009_sitename'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitename',
            name='theme',
            field=models.CharField(blank=True, help_text='Set site theme.', max_length=128, null=True),
        ),
    ]
