# Generated by Django 3.1.8 on 2021-04-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0009_sitename'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='value_type',
            field=models.CharField(choices=[('0', ''), ('1', 'Boolean'), ('2', 'Number'), ('3', 'Text')], default=0, max_length=10),
        ),
    ]
