# Generated by Django 3.1.8 on 2021-04-19 16:10

from django.db import migrations

def create_inactivity_timeout(apps, schema_editor):
    SystemSettings = apps.get_model('system_settings', 'SystemSettings')
    inactivity_timeout = SystemSettings.objects.create(setting="inactivity_timeout", active=True, value=1800, value_type="2", description="Inactivity timeout in seconds. This is used to automatically logout user.")
    inactivity_timeout.save()

class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0010_auto_20210419_1607'),
    ]

    operations = [ migrations.RunPython(create_inactivity_timeout, migrations.RunPython.noop) ]
