# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(help_text="The ID of the question (with the Task's module) that this Answer answers.", max_length=128)),
                ('value', jsonfield.fields.JSONField(blank=True, help_text='The actual answer value for the Question, or None/null if the question is not really answered yet.')),
                ('notes', models.TextField(blank=True, help_text='Notes entered by the user completing this Answer.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, help_text='The name of an emoji that the user is reacting with.', max_length=64, null=True)),
                ('text', models.TextField(blank=True, help_text="The text of the user's comment.")),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('target', models.ForeignKey(help_text='The Answer that this comment is attached to.', on_delete=django.db.models.deletion.CASCADE, to='guidedmodules.Answer')),
                ('user', models.ForeignKey(help_text='The user making a comment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(help_text='The ID of the module being completed.', max_length=128)),
                ('requestor_notes', models.TextField(blank=True, help_text='A message from the requesting user to the user of this Task.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('requested_by', models.ForeignKey(blank=True, help_text='The Answer that this sub-Task is trying to answer, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requesting_tasks', to='guidedmodules.Answer')),
                ('user', models.ForeignKey(help_text='The user that is working on this task.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(help_text='The Task that this Answer is for.', on_delete=django.db.models.deletion.CASCADE, to='guidedmodules.Task'),
        ),
    ]
