# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emojis', models.CharField(blank=True, help_text='A comma-separated list of emoji names that the user is reacting with.', max_length=256, null=True)),
                ('text', models.TextField(blank=True, help_text="The text of the user's comment.")),
                ('proposed_answer', jsonfield.fields.JSONField(blank=True, help_text='A proposed answer to the question that this discussion is about.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_participants', models.ManyToManyField(blank=True, help_text='Additional Users who are participating in this chat, besides those that are members of the Project that contains the Discussion.', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_question_id', models.CharField(blank=True, help_text='The ID of the question that prompted the invitation.', max_length=64, null=True)),
                ('into_project', models.BooleanField(default=False, help_text='Whether the user being invited is being invited to join from_project.')),
                ('into_new_task_module_id', models.CharField(blank=True, help_text='The ID of the module that the recipient is being asked to complete, if any.', max_length=128, null=True)),
                ('to_email', models.CharField(blank=True, help_text='The email address the invitation was sent to, if to a non-existing user.', max_length=256, null=True)),
                ('text', models.TextField(blank=True, help_text='The personalized text of the invitation.')),
                ('sent_at', models.DateTimeField(blank=True, help_text='If the invitation has been sent by email, when it was sent.', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='If the invitation has been accepted, when it was accepted.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='If the invitation has been revoked, when it was revoked.', null=True)),
                ('email_invitation_code', models.CharField(blank=True, help_text='For emails, a unique verification code.', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this Project.', max_length=256)),
                ('notes', models.TextField(blank=True, help_text='Notes about this Project for Project members.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, help_text='Is the user an administrator of the Project?')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('project', models.ForeignKey(help_text='The Project this is defining membership for.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='guidedmodules.Project')),
                ('user', models.ForeignKey(help_text='The user that is a member of the Project.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(help_text='The ID of the module being completed.', max_length=128)),
                ('title', models.CharField(help_text='The title of this Task. If the user is performing multiple tasks for the same module, this title would distiguish the tasks.', max_length=256)),
                ('notes', models.TextField(blank=True, help_text='Notes set by the user about why they are completing this task.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('editor', models.ForeignKey(help_text='The user that has primary responsibility for completing this Task.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='The Project that this Task is a part of, or empty for Tasks that are just directly owned by the user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='guidedmodules.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', jsonfield.fields.JSONField(blank=True, help_text='The actual answer value for the Question, or None/null if the question is not really answered yet.')),
                ('notes', models.TextField(blank=True, help_text='Notes entered by the user completing this TaskAnswer.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('answered_by', models.ForeignKey(help_text='The user that provided this answer.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('answered_by_task', models.ForeignKey(blank=True, help_text='A Task that supplies the answer for this question.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_answer_to', to='guidedmodules.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(help_text="The ID of the question (within the Task's module) that this TaskQuestion represents.", max_length=128)),
                ('notes', models.TextField(blank=True, help_text='Notes entered by editors working on this question.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('task', models.ForeignKey(help_text='The Task that this TaskQuestion is a part of.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='guidedmodules.Task')),
            ],
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='question',
            field=models.ForeignKey(help_text='The TaskQuestion that this is an aswer to.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='guidedmodules.TaskQuestion'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='accepted_task',
            field=models.ForeignKey(blank=True, help_text='The Task generated by accepting the invitation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to='guidedmodules.Task'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='accepted_user',
            field=models.ForeignKey(blank=True, help_text='The user that accepted the invitation (i.e. if the invitation was by email address and an account was created).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='from_project',
            field=models.ForeignKey(help_text='The Project within which the invitation exists.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='guidedmodules.Project'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='from_user',
            field=models.ForeignKey(help_text='The User who sent the invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='into_discussion',
            field=models.ForeignKey(blank=True, help_text='The Discussion that the recipient is being invited to join, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='guidedmodules.Discussion'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='into_task_editorship',
            field=models.ForeignKey(blank=True, help_text='The Task that the recipient is being invited to take editorship over, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_to_take_over', to='guidedmodules.Task'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='prompt_task',
            field=models.ForeignKey(blank=True, help_text='The Task that prompted the invitation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_prompted', to='guidedmodules.Task'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(blank=True, help_text='The user who the invitation was sent to, if to an existing user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='for_question',
            field=models.OneToOneField(blank=True, help_text='The TaskQuestion that this discussion thread is for.', on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='guidedmodules.TaskQuestion'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='project',
            field=models.ForeignKey(help_text='The Project that this Discussion exists within.', on_delete=django.db.models.deletion.CASCADE, to='guidedmodules.Project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(help_text='The Discussion that this comment is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='guidedmodules.Discussion'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies_to',
            field=models.ForeignKey(blank=True, help_text='If this is a reply to a Comment, the Comment that this is in reply to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='guidedmodules.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='The user making a comment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='taskquestion',
            unique_together=set([('task', 'question_id')]),
        ),
        migrations.AlterIndexTogether(
            name='task',
            index_together=set([('project', 'editor', 'module_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together=set([('project', 'user')]),
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('discussion', 'user')]),
        ),
    ]
