# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes set by the user about why they are completing this task.'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='title', help_text='The title of this Task. If the user is performing multiple tasks for the same module, this title would distiguish the tasks.', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('task', 'question_id')]),
        ),
    ]
