# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered_by_task',
            field=models.ForeignKey(blank=True, help_text='A Task that supplies the answer for this question.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_answer_of', to='guidedmodules.Task'),
        ),
    ]
