# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guidedmodules', '0001_initial'),
        ('siteapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswer',
            name='answered_by',
            field=models.ForeignKey(help_text='The user that provided this answer.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='answered_by_task',
            field=models.ForeignKey(blank=True, help_text='A Task that supplies the answer for this question.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_answer_to', to='guidedmodules.Task'),
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='question',
            field=models.ForeignKey(help_text='The TaskQuestion that this is an aswer to.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='guidedmodules.TaskQuestion'),
        ),
        migrations.AddField(
            model_name='task',
            name='editor',
            field=models.ForeignKey(help_text='The user that has primary responsibility for completing this Task.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='invitation_history',
            field=models.ManyToManyField(blank=True, help_text='The history of accepted invitations that had this Task as a target.', to='siteapp.Invitation'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The Project that this Task is a part of, or empty for Tasks that are just directly owned by the user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='taskquestion',
            unique_together=set([('task', 'question_id')]),
        ),
        migrations.AlterIndexTogether(
            name='task',
            index_together=set([('project', 'editor', 'module_id')]),
        ),
    ]
