# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(default=False, help_text="Set to true if the comment has been 'deleted'."),
        ),
    ]
