# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guidedmodules', '0002_auto_20160428_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this Project.', max_length=256)),
                ('notes', models.TextField(blank=True, help_text='Notes about this Project for Project members.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, help_text='Is the user an administrator of the Project?')),
                ('project', models.ForeignKey(help_text='The Project this is defining membership for.', on_delete=django.db.models.deletion.CASCADE, to='guidedmodules.Project')),
                ('user', models.ForeignKey(help_text='The user that is a member of the Project.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('user', 'target')]),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The Project that this Task is a part of, or empty for Tasks that are just directly owned by the user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='guidedmodules.Project'),
        ),
        migrations.AlterIndexTogether(
            name='task',
            index_together=set([('project', 'user', 'module_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together=set([('project', 'user')]),
        ),
    ]
