# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guidedmodules', '0002_answer_answered_by_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered_by',
            field=models.ForeignKey(default=None, help_text='The user that provided this answer.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='history',
            field=jsonfield.fields.JSONField(blank=True, default=[], help_text='A history of this Answer, as a list of dicts with keys that are the same as the model fields.'),
        ),
    ]
