# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0002_auto_20160518_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="If 'deleted' by a user, the date & time the Task was deleted.", null=True),
        ),
    ]
