# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0003_auto_20160508_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(help_text='The Discussion that this comment is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='guidedmodules.Discussion'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replies_to',
            field=models.ForeignKey(blank=True, help_text='If this is a reply to a Comment, the Comment that this is in reply to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='guidedmodules.Comment'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='for_answer',
            field=models.OneToOneField(blank=True, help_text='The Answer that this discussion thread is for.', on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='guidedmodules.Answer'),
        ),
    ]
