# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0003_auto_20160429_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, default=None),
            preserve_default=False,
        ),
    ]
