# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0004_auto_20160605_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswerhistory',
            name='cleared',
            field=models.BooleanField(default=False, help_text="Set to True to indicate that the user wants to clear their answer. This is different from a null-valued answer, which means not applicable/don't know/skip."),
        ),
    ]
