# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guidedmodules', '0004_auto_20160429_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(blank=True, help_text='The ID of the question that prompted the invitation.', max_length=64, null=True)),
                ('to_email', models.CharField(blank=True, help_text='The email address the invitation was sent to, if to a non-existing user.', max_length=256, null=True)),
                ('text', models.TextField(blank=True, help_text='The personalized text of the invitation.')),
                ('sent_at', models.DateTimeField(blank=True, help_text='If the invitation has been sent by email, when it was sent.', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='If the invitation has been accepted, when it was accepted.', null=True)),
                ('email_invitation_code', models.CharField(blank=True, help_text='For emails, a unique verification code.', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
            ],
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='project',
            field=models.ForeignKey(help_text='The Project this is defining membership for.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='guidedmodules.Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='The Task (and its user) which is requesting that this Task be completed, if applicable. Answers are inherited from this Task if there is no Answer for a particular question in this Task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='guidedmodules.Task'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='accepted_task',
            field=models.ForeignKey(blank=True, help_text='The Task generated by accepting the invitation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to='guidedmodules.Task'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='accepted_user',
            field=models.ForeignKey(blank=True, help_text='The user that accepted the invitation (i.e. if the invitation was by email address).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='from_task',
            field=models.ForeignKey(help_text='The Task that prompted the invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='guidedmodules.Task'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='from_user',
            field=models.ForeignKey(help_text='The user who sent the invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(blank=True, help_text='The user who the invitation was sent to, if to an existing user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
