# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0005_taskanswerhistory_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='The Project that this Task is a part of, or empty for Tasks that are just directly owned by the user.', on_delete=django.db.models.deletion.CASCADE, to='siteapp.Project'),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='task',
            field=models.ForeignKey(help_text='The Task that this TaskAnswer is a part of.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='guidedmodules.Task'),
        ),
        migrations.AlterField(
            model_name='taskanswerhistory',
            name='taskanswer',
            field=models.ForeignKey(help_text='The TaskAnswer that this is an aswer to.', on_delete=django.db.models.deletion.CASCADE, related_name='answer_history', to='guidedmodules.TaskAnswer'),
        ),
    ]
