# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0005_auto_20160502_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='from_project',
            field=models.ForeignKey(blank=True, help_text='The Project that the user being invited is being invited to join, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='guidedmodules.Project'),
        ),
    ]
