# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_remove_project_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guidedmodules', '0006_auto_20160610_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(max_length=32)),
                ('event_value', models.FloatField(null=True)),
                ('extra', jsonfield.fields.JSONField(help_text='Additional un-indexed data.')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guidedmodules.TaskAnswer')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guidedmodules.Module')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteapp.Project')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guidedmodules.ModuleQuestion')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guidedmodules.Task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='instrumentationevent',
            index_together=set([('module', 'event_type', 'event_time'), ('event_type', 'event_time'), ('project', 'event_type', 'event_time')]),
        ),
    ]
