# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0006_invitation_from_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='from_project',
            new_name='invite_to_project',
        ),
    ]
