# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0008_auto_20160617_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswerhistory',
            name='answered_by_reference',
            field=models.ForeignKey(blank=True, help_text='The answer to this question is determined by looking at the value of the current answer to the referenced question.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='guidedmodules.TaskAnswer'),
        ),
    ]
