# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0009_taskanswerhistory_answered_by_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswerhistory',
            name='answered_by_file',
            field=models.FileField(blank=True, null=True, upload_to='q/files'),
        ),
        migrations.AddField(
            model_name='taskanswerhistory',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='q/thumbnails'),
        ),
    ]
