# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0011_modulequestion_answer_type_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskanswerhistory',
            name='answered_by_reference',
        ),
    ]
