# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-02 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

# This migration didn't work right - It assigned the same UUID to every
# task. Fixed with: for t in Task.objects.all(): t.uuid = uuid.uuid4(); t.save()

class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0012_remove_taskanswerhistory_answered_by_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A UUID (a unique identifier) for this Task, used to synchronize Task content between systems.'),
        ),
    ]
