# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 14:37
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0013_task_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswerhistory',
            name='stored_encoding',
            field=jsonfield.fields.JSONField(blank=True, default=None, help_text='If not null, this field describes how stored_value is encoded and/or encrypted.', null=True),
        ),
    ]
