# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0017_auto_20170313_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesource',
            name='trust_javascript_assets',
            field=models.BooleanField(default=False, help_text='Are new Javascript static assets loaded from this source trusted to be served on our domain and run client side?'),
        ),
    ]
