# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0015_remove_organization_allowed_modules'),
        ('guidedmodules', '0018_modulesource_trust_javascript_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesource',
            name='available_to_all',
            field=models.BooleanField(default=True, help_text='Turn off to restrict the Modules loaded from this source to particular organizations.'),
        ),
        migrations.AddField(
            model_name='modulesource',
            name='available_to_orgs',
            field=models.ManyToManyField(blank=True, help_text='If available_to_all is False, list the Organizations that can start projects defined by Modules provided by this ModuleSource.', to='siteapp.Organization'),
        ),
    ]
