# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0019_auto_20170501_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='key',
            field=models.SlugField(help_text='A slug-like identifier for the Module.', max_length=200),
        ),
    ]
