# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0020_auto_20170523_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='The Project that this Task is a part of, or empty for Tasks that are just directly owned by the user.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='siteapp.Project'),
        ),
    ]
