# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0021_auto_20170612_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='editor',
            field=models.ForeignKey(help_text='The user that has primary responsibility for completing this Task.', on_delete=django.db.models.deletion.PROTECT, related_name='tasks_editor_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
