# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0022_auto_20170613_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswerhistory',
            name='answered_by_method',
            field=models.CharField(choices=[('web', 'Web'), ('imp', 'Import'), ('api', 'API')], default='web', help_text='How this answer was submitted, via the website by a user, via the Export/Import mechanism, or via an API programmatically.', max_length=3),
            preserve_default=False,
        ),
    ]
