# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0023_taskanswerhistory_answered_by_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswerhistory',
            name='reviewed',
            field=models.IntegerField(default=0, help_text="Whether this answer has been reviewed and/or approved. All new answers begin with zero. Positive values represent review steps in the organization's workflow."),
        ),
    ]
