# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0025_auto_20170831_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulesource',
            old_name='trust_javascript_assets',
            new_name='trust_assets',
        ),
        migrations.AlterField(
            model_name='modulesource',
            name='trust_assets',
            field=models.BooleanField(default=False, help_text="Are assets trusted? Assets include Javascript that will be served on our domain, Python code included with Modules, and Jinja2 templates in Modules."),
        ),
        migrations.AddField(
            model_name='moduleassetpack',
            name='trust_assets',
            field=models.BooleanField(default=False, help_text="Are assets trusted? Assets include Javascript that will be served on our domain, Python code included with Modules, and Jinja2 templates in Modules."),
        ),
    ]
