# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('guidedmodules', '0026_auto_20170906_1930'),
    ]

    operations = [
    	migrations.RenameModel('ModuleSource', 'AppSource')
    ]
