# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0027_modulesource_to_appsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(db_index=True, help_text='The name of the app in the AppStore.', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='appinstance',
            name='source',
            field=models.ForeignKey(help_text='The source of this AppInstance.', on_delete=django.db.models.deletion.CASCADE, related_name='appinstances', to='guidedmodules.AppSource'),
        ),
        migrations.AddField(
            model_name='module',
            name='app',
            field=models.ForeignKey(help_text='The AppInstance that this Module is a part of. Null for legacy Modules created before we had this field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='guidedmodules.AppInstance'),
        ),
    ]
