# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0028_auto_20170908_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsource',
            name='available_to_orgs',
            field=models.ManyToManyField(blank=True, help_text='If available_to_all is False, list the Organizations that can start projects defined by Modules provided by this AppSource.', to='siteapp.Organization'),
        ),
        migrations.AlterField(
            model_name='modulequestion',
            name='module',
            field=models.ForeignKey(help_text='The Module that this ModuleQuestion is a part of.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='guidedmodules.Module'),
        ),
    ]
