# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-23 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0030_module_key_rename_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='visible',
        ),
        migrations.AddField(
            model_name='appinstance',
            name='system_app',
            field=models.NullBooleanField(default=None, help_text='Set to True for AppInstances that are the current version of a system app that provides system-expected Modules. A constraint ensures that only one (source, name) pair can be true.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='This field is no longer used. When a Module is superseded by a new version, this points to the newer version.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='guidedmodules.Module'),
        ),
        migrations.AlterUniqueTogether(
            name='appinstance',
            unique_together=set([('source', 'appname', 'system_app')]),
        ),
    ]
