# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-29 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0031_auto_20171023_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswerhistory',
            name='reviewed',
            field=models.IntegerField(choices=[(0, 'Not Reviewed'), (1, 'Reviewed'), (2, 'Approved')], default=0, help_text="Whether this answer has been reviewed and/or approved. All new answers begin with zero. Positive values represent review steps in the organization's workflow."),
        ),
    ]
