# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0032_auto_20171029_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskanswerhistory',
            options={'verbose_name_plural': 'TaskAnswerHistories'},
        ),
    ]
