# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-14 18:40
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0034_title_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cached_is_finished',
        ),
        migrations.AddField(
            model_name='task',
            name='cached_state',
            field=jsonfield.fields.JSONField(blank=True, default=None, help_text='Cached value storing whether the Task is finished, its computed title, and other state that depends on question answers.'),
        ),
    ]
