# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-05 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0035_auto_20171214_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstance',
            name='appname',
            field=models.CharField(db_index=True, help_text='The name of the app in the AppSource.', max_length=200),
        ),
    ]
