# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0037_appsource_is_system_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsource',
            old_name='namespace',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='appsource',
            name='slug',
            field=models.CharField(help_text='A unique URL-safe string that names this AppSource.', max_length=200, unique=True),
        ),
    ]
