# Generated by Django 2.0.2 on 2018-03-12 21:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0038_auto_20180126_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsource',
            name='approved_apps',
            field=jsonfield.fields.JSONField(default={}, blank=True, help_text='Information about apps whitelisted or blacklisted for display in the catalog from this source.'),
        ),
    ]
