# Generated by Django 2.0.2 on 2018-04-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('guidedmodules', '0040_auto_20180409_0157'), ('guidedmodules', '0041_auto_20180409_1707')]

    dependencies = [
        ('guidedmodules', '0039_appsource_approved_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswerhistory',
            name='skipped_reason',
            field=models.CharField(blank=True, choices=[('dont-know', "Don't Know"), ('doesnt-apply', "Doesn't Apply"), ('come-back', 'Come Back Later')], help_text='The reason no answer was given.', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='taskanswerhistory',
            name='unsure',
            field=models.BooleanField(default=False, help_text="A flag for if the user wasn't sure the answer is correct and should come back to it later."),
        ),
    ]
