# Generated by Django 2.0.3 on 2018-04-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0040_auto_20180409_0157_squashed_0041_auto_20180409_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswerhistory',
            name='answered_by_method',
            field=models.CharField(choices=[('web', 'Web'), ('imp', 'Import'), ('api', 'API'), ('delete', 'Task Deletion')], help_text='How this answer was submitted, via the website by a user, via the Export/Import mechanism, or via an API programmatically.', max_length=3),
        ),
    ]
