# Generated by Django 2.0.5 on 2018-05-22 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0042_auto_20180430_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appinstance',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
