# Generated by Django 2.0.9 on 2019-04-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0047_auto_20190403_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='show_in_catalog',
            field=models.BooleanField(default=False, help_text='Whether to show this AppVersion in the compliane app catalog, which allows users to start the app.'),
        ),
        migrations.RemoveField(
            model_name='appsource',
            name='approved_apps',
        ),
    ]
