# Generated by Django 2.2.10 on 2020-04-04 16:28

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0048_appversion_show_in_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsource',
            name='spec',
            field=jsonfield.fields.JSONField(help_text='A load_modules ModuleRepository spec.', load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='module',
            name='spec',
            field=jsonfield.fields.JSONField(help_text='Module definition data.', load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='modulequestion',
            name='spec',
            field=jsonfield.fields.JSONField(help_text='Module definition data.', load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
