# Generated by Django 3.0.7 on 2020-11-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0049_auto_20200404_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswerhistory',
            name='taskanswer',
            field=models.ForeignKey(help_text='The TaskAnswer that this is an answer to.', on_delete=django.db.models.deletion.CASCADE, related_name='answer_history', to='guidedmodules.TaskAnswer'),
        ),
    ]
