# Generated by Django 3.0.7 on 2020-11-08 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guidedmodules', '0049_auto_20200404_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsource',
            name='available_to_all_individuals',
            field=models.BooleanField(default=True, help_text='Turn off to restrict the Modules loaded from this source to particular individuals.'),
        ),
        migrations.AddField(
            model_name='appsource',
            name='available_to_individual',
            field=models.ManyToManyField(blank=True, help_text='If available_to_all_individuals is False, list the individuals that can start projects defined by Modules provided by this AppSource.', related_name='individual', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appsource',
            name='available_to_role',
            field=models.BooleanField(default=True, help_text='Turn off to restrict the ability to start projects defined by Modules provided by this AppSource.'),
        ),
    ]
