# Generated by Django 3.0.7 on 2020-12-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0050_auto_20201103_1327'),
        ('guidedmodules', '0050_auto_20201108_1531'),
    ]

    operations = [
    ]
