# Generated by Django 3.0.7 on 2020-12-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0051_merge_20201201_2323'),
        ('guidedmodules', '0051_auto_20201113_1518'),
    ]

    operations = [
    ]
