# Generated by Django 3.0.11 on 2021-01-22 15:02

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0036_historicalstatement'),
        ('guidedmodules', '0052_merge_20201210_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='input_artifacts',
            field=models.ManyToManyField(help_text='The objects created from this input.', related_name='import_records', to='controls.ImportRecord'),
        ),
        migrations.AddField(
            model_name='appversion',
            name='input_paths',
            field=jsonfield.fields.JSONField(blank=True, help_text='A dictionary mapping file paths to the content_hashes of inputs included in the inputs field of this instance.', null=True),
        ),
        migrations.AddField(
            model_name='appversion',
            name='trust_inputs',
            field=models.BooleanField(default=False, help_text='Are inputs trusted? Inputs include OSCAL components and statements that will be served on our domain.', null=True),
        ),
        migrations.CreateModel(
            name='AppInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.SlugField(help_text='A slug-like identifier for the input that is unique within the AppVersion app.', max_length=200)),
                ('content_hash', models.CharField(help_text='A hash of the input binary content, as provided by the source.', max_length=64)),
                ('file', models.FileField(help_text='The input file.', upload_to='guidedmodules/app-inputs')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('app', models.ForeignKey(help_text='The AppVersion that this input is a part of.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='guidedmodules.AppVersion')),
                ('source', models.ForeignKey(help_text='The source of this app input.', on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='guidedmodules.AppSource')),
            ],
            options={
                'unique_together': {('source', 'content_hash')},
            },
        ),
        migrations.AddField(
            model_name='appversion',
            name='input_files',
            field=models.ManyToManyField(help_text='The inputs linked to this pack.', to='guidedmodules.AppInput'),
        ),
    ]
