# Generated by Django 3.0.11 on 2021-02-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0053_auto_20210122_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='input_files',
            field=models.ManyToManyField(blank=True, help_text='The inputs linked to this pack.', null=True, to='guidedmodules.AppInput'),
        ),
    ]
