# Generated by Django 3.0.11 on 2021-01-21 23:12

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0036_historicalstatement'),
        ('guidedmodules', '0054_auto_20210121_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='input_artifacts',
            field=models.ForeignKey(blank=True, help_text='The objects created from this input.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_records', to='controls.ImportRecord'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='input_paths',
            field=jsonfield.fields.JSONField(blank=True, help_text='A dictionary mapping file paths to the content_hashes of inputs included in the inputs field of this instance.', null=True),
        ),
    ]
