# Generated by Django 3.0.11 on 2021-03-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0054_auto_20210211_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='input_files',
            field=models.ManyToManyField(blank=True, help_text='The inputs linked to this pack.', to='guidedmodules.AppInput'),
        ),
    ]
