# Generated by Django 3.0.11 on 2021-01-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0055_auto_20210121_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appversion',
            name='input_artifacts',
        ),
    ]
