# Generated by Django 3.0.11 on 2021-01-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0036_historicalstatement'),
        ('guidedmodules', '0056_remove_appversion_input_artifacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='input_artifacts',
            field=models.ManyToManyField(help_text='The objects created from this input.', related_name='import_records', to='controls.ImportRecord'),
        ),
    ]
