# Generated by Django 3.1.7 on 2021-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0056_auto_20210310_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='system_app',
            field=models.BooleanField(default=None, help_text='Set to True for AppVersions that are the current version of a system app that provides system-expected Modules. A constraint ensures that only one (source, name) pair can be true.', null=True),
        ),
    ]
