# Generated by Django 3.1.8 on 2021-04-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0057_auto_20210413_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinput',
            name='input_type',
            field=models.CharField(blank=True, choices=[('OSCAL', 'oscal'), ('POAM', 'poam')], help_text='Type of input (oscal, poam)', max_length=64, null=True),
        ),
    ]
