# Generated by Django 3.2.5 on 2021-10-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0058_appinput_input_type'),
        ('guidedmodules', '0058_auto_20210423_1555'),
    ]

    operations = [
    ]
