# Generated by Django 3.2.10 on 2022-01-01 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guidedmodules', '0060_alter_moduleasset_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulequestion',
            name='answer_type_module',
            field=models.ForeignKey(blank=True, help_text='For module and module-set typed questions, this is the Module that Tasks that answer this question must be for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_type_of_answer_to', to='guidedmodules.module'),
        ),
        migrations.AlterField(
            model_name='task',
            name='editor',
            field=models.ForeignKey(help_text='The user that has primary responsibility for completing this Task.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks_editor_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='module',
            field=models.ForeignKey(help_text='The Module that this Task is answering.', on_delete=django.db.models.deletion.CASCADE, to='guidedmodules.module'),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='question',
            field=models.ForeignKey(help_text="The question (within the Task's Module) that this TaskAnswer is answering.", on_delete=django.db.models.deletion.CASCADE, to='guidedmodules.modulequestion'),
        ),
        migrations.AlterField(
            model_name='taskanswerhistory',
            name='answered_by',
            field=models.ForeignKey(help_text='The user that provided this answer.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
