# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_account_project',
            field=models.BooleanField(default=False, help_text='Each User has one Project for account Tasks.'),
        ),
    ]
