# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_auto_20160605_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='notes',
        ),
    ]
