# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-29 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_remove_project_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name of the Organization.', max_length=256)),
                ('subdomain', models.CharField(help_text='The subdomain of q.govready.com that this Organization exists at.', max_length=256)),
            ],
        ),
    ]
