# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 20:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0007_auto_20160730_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2016, 11, 4, 20, 46, 12, 820992, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='extra',
            field=jsonfield.fields.JSONField(default={}, help_text='Additional information stored with this object.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2016, 11, 4, 20, 46, 17, 132718, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
