# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0008_auto_20161104_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifemails_enabled',
            field=models.IntegerField(choices=[(0, 'As They Happen'), (1, "Don't Email")], default=0, help_text='How often to email the user notification emails.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notifemails_last_at',
            field=models.DateTimeField(blank=True, default=None, help_text='The time when the last notification email was sent to the user.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notifemails_last_notif_id',
            field=models.PositiveIntegerField(default=0, help_text='The primary key of the last notifications.Notification sent by email.'),
        ),
    ]
