# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 15:40
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0009_auto_20161105_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text='Additional information stored with this object.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
