# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0010_auto_20161207_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allowed_modules',
            field=models.TextField(default='', help_text='A list of module keys of `access: private` project modules that this Organization has permission to use, separated by spaces or newlines.'),
        ),
    ]
