# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0013_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='admin_users',
            field=models.ManyToManyField(blank=True, help_text='Users who have admin privs to the folder besides those who are admins of projects within the folder.', related_name='admin_of_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='The Projects that are listed within this Folder.', related_name='contained_in_folders', to='siteapp.Project'),
        ),
    ]
