# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0015_remove_organization_allowed_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.CharField(blank=True, help_text='A description of this Folder.', max_length=512),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(help_text='The title of this Folder.', max_length=256),
        ),
    ]
