# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 19:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0016_auto_20170505_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(help_text="The subdomain of the host site that this Organization's site is served at.", max_length=256, unique=True, validators=[django.core.validators.RegexValidator(regex='^([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\\-]*[a-zA-Z0-9])$')]),
        ),
    ]
