# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0017_auto_20170612_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key_ro',
            field=models.CharField(blank=True, help_text="The user's API key with read-only permission.", max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='api_key_rw',
            field=models.CharField(blank=True, help_text="The user's API key with read-write permission.", max_length=32, null=True, unique=True),
        ),
    ]
