# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0018_auto_20170811_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key_wo',
            field=models.CharField(blank=True, help_text="The user's API key with write-only permission.", max_length=32, null=True, unique=True),
        ),
    ]
