# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0019_user_api_key_wo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='help_squad',
            field=models.ManyToManyField(blank=True, help_text='Users who are invited to all new discussions in this Organization.', to=settings.AUTH_USER_MODEL),
        ),
    ]
