# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-29 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0020_organization_help_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text='Users who are permitted to change the reviewed state of task answers.', related_name='is_reviewer_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='help_squad',
            field=models.ManyToManyField(blank=True, help_text='Users who are invited to all new discussions in this Organization.', related_name='in_help_squad_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
