# Generated by Django 2.0.2 on 2018-03-15 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0023_auto_20180212_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(help_text="The subdomain of the host site that this Organization's site is served at.", max_length=200, unique=True, validators=[django.core.validators.RegexValidator(regex='^([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\\-]*[a-zA-Z0-9])$')]),
        ),
    ]
