# Generated by Django 2.0.10 on 2019-05-15 14:55

from django.db import migrations, models

# Generated by Django 2.0.10 on 2019-05-15 14:46

from django.db import migrations

def forward(apps, schema_editor):
    # User profile Projects were unique for each (User, Organization) pair. Make
    # them unique per User by keeping only the first one for each User.
    Project = apps.get_model("siteapp", "Project")
    profiles = Project.objects\
      .filter(is_account_project=True)\
      .order_by('created')\
      .values("id", "members__user")
    seen_users = set()
    profiles_to_keep = set()
    profiles_to_delete = set()
    for profile in profiles:
        if profile["members__user"] not in seen_users:
            # This is the first one we encountered for this user. Keep it.
            seen_users.add(profile["members__user"])
            profiles_to_keep.add(profile["id"])
        else:
            # Queue this profile for deletion.
            profiles_to_delete.add(profile["id"])

    # Disassociate the profiles we're keeping from any Organization
    Project.objects.filter(id__in=profiles_to_keep).update(organization=None)

    # Delete the ones that now redundant.
    Project.objects.filter(id__in=profiles_to_delete).delete()

def backward(apps, schema_editor):
    # We can't recreate profiles that we've deleted. And since the
    # migration made the organization column nullable, we can't
    # regress because the user profile projects now have null
    # in that column. The only solution would be to delete the
    # remaining user profile Projects so that the NOT NULL
    # constraint is not violated.
    apps.get_model("siteapp", "Project")\
        .objects\
        .filter(is_account_project=True)\
        .delete()

class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0024_auto_20180315_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The Organization that this Project belongs to. User profiles (is_account_project is True) are not a part of any Organization.', null=True, on_delete=models.deletion.CASCADE, related_name='projects', to='siteapp.Organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_account_project',
            field=models.BooleanField(default=False, help_text='Each User has one Project for account Tasks.'),
        ),
        migrations.RunPython(forward, backward),
    ]
