# Generated by Django 2.0.13 on 2019-05-15 19:35

from django.db import migrations, models
import django.core.validators

class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0025_auto_20190515_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='subdomain',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.CharField(help_text='A URL-safe abbreviation for the Organization.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(regex='^([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\\-]*[a-zA-Z0-9])$')]),
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='organization',
        ),
    ]
