# Generated by Django 2.2.4 on 2019-10-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0006_auto_20191021_0649'),
        ('siteapp', '0032_auto_20191024_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='systeminstance',
            field=models.ForeignKey(blank=True, help_text='The IT System to which this Projectis associated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='itsystems.SystemInstance'),
        ),
    ]
