# Generated by Django 2.2.12 on 2020-05-04 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0014_auto_20200504_0003'),
        ('siteapp', '0032_auto_20191024_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='system',
            field=models.ForeignKey(blank=True, help_text='The System that this Project is about.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='controls.System'),
        ),
    ]
