# Generated by Django 3.0.7 on 2020-08-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0035_auto_20200807_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='text',
            field=models.TextField(blank=True, help_text='Text or HTML content to appear at top of support page', null=True),
        ),
    ]
