# Generated by Django 3.0.7 on 2020-10-14 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0036_auto_20200819_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the remote service', max_length=255)),
                ('connection_url', models.URLField(help_text='Web address of service connection')),
                ('access_token_or_identifier', models.CharField(help_text='Access token, identifier, or username for authentication', max_length=255)),
                ('access_token_secret', models.CharField(help_text='Access token secret or password for authentication', max_length=255)),
                ('service_type', models.IntegerField(choices=[(0, 'Other'), (1, 'GitLab'), (2, 'GitHub')], default=1, help_text='Type of remote service')),
                ('user', models.ForeignKey(help_text='The User who owns this remote service account.', on_delete=django.db.models.deletion.CASCADE, related_name='remote_service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='remote_services',
            field=models.ManyToManyField(blank=True, help_text='Associated remote services.', related_name='projects', to='siteapp.RemoteService'),
        ),
    ]
