# Generated by Django 3.0.7 on 2020-10-07 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0036_auto_20200819_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the remote service', max_length=255)),
                ('url', models.URLField(help_text='Web address of home page')),
                ('connection_url', models.URLField(help_text='Web address of service connection')),
                ('access_token', models.CharField(help_text='Access token or username for authentication', max_length=255)),
                ('access_token_secret', models.CharField(blank=True, help_text='Access token secret or password for authentication (optional)', max_length=255, null=True)),
                ('service_type', models.IntegerField(choices=[(1, 'GitLab'), (2, 'GitHub'), (0, 'Other')], default=0, help_text='Type of remote service')),
                ('user', models.ForeignKey(help_text='The User who owns this remote service account.', on_delete=django.db.models.deletion.CASCADE, related_name='remote_service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
