# Generated by Django 3.0.7 on 2020-11-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0033_project_systeminstance'),
        ('siteapp', '0032_auto_20191025_1723'),
        ('siteapp', '0036_auto_20200819_1806'),
    ]

    operations = [
    ]
