# Generated by Django 3.0.7 on 2020-11-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0036_auto_20200819_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_key', models.CharField(max_length=255, unique=True)),
                ('parameter_key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=1024)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.Organization')),
            ],
            options={
                'db_table': 'organizational_setting',
            },
        ),
    ]
