# Generated by Django 3.0.7 on 2020-10-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0037_remoteservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remote_services',
            field=models.ManyToManyField(blank=True, help_text='Associated remote services.', related_name='projects', to='siteapp.RemoteService'),
        ),
    ]
