# Generated by Django 3.0.11 on 2021-01-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0038_auto_20210114_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalsetting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_setting', to='siteapp.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationalsetting',
            name='value',
            field=models.TextField(),
        ),
    ]
