# Generated by Django 3.1.6 on 2021-02-28 16:35

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0039_auto_20210120_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this asset.', max_length=255)),
                ('asset_type', models.CharField(choices=[('SSP_EXPORT', 'SSP Export')], help_text='Asset type.', max_length=150)),
                ('content_hash', models.CharField(help_text='A hash of the asset binary content, as provided by the source.', max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(help_text='The attached file.', upload_to=None)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A UUID (a unique identifier) for this Asset.')),
                ('default', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='siteapp.project')),
            ],
            options={
                'unique_together': {('title', 'project')},
            },
        ),
    ]
