# Generated by Django 3.1.7 on 2021-03-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0040_auto_20210228_1635'),
        ('siteapp', '0040_auto_20210301_1635'),
    ]

    operations = [
    ]
