# Generated by Django 3.1.7 on 2021-03-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0041_merge_20210301_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectasset',
            name='content_hash',
            field=models.CharField(help_text='A hash of the asset binary content, as provided by the source.', max_length=128),
        ),
    ]
