# Generated by Django 3.1.7 on 2021-03-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0043_auto_20210310_1652'),
        ('siteapp', '0041_project_tags'),
    ]

    operations = [
    ]
