# Generated by Django 3.1.7 on 2021-03-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0043_auto_20210310_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
