# Generated by Django 3.1.8 on 2021-04-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0044_auto_20210314_1952'),
        ('siteapp', '0044_merge_20210313_0904'),
    ]

    operations = [
    ]
