# Generated by Django 3.1.8 on 2021-04-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0045_auto_20210408_1958'),
    ]

    operations = [
    ]
