# Generated by Django 3.1.7 on 2021-04-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0044_merge_20210313_0904'),
        ('siteapp', '0045_auto_20210408_1958'),
    ]

    operations = [
    ]
