# Generated by Django 3.1.7 on 2021-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0046_merge_20210413_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_organization_project',
            field=models.BooleanField(default=None, help_text='Each Organization has one Project that holds Organization membership privileges and Organization settings (in its root Task). In order to have a unique_together constraint with Organization, only the values None (which need not be unique) and True (which must be unique to an Organization) are used.', null=True),
        ),
    ]
