# Generated by Django 3.1.7 on 2021-04-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0046_merge_20210410_1508'),
        ('siteapp', '0047_auto_20210413_1504'),
    ]

    operations = [
    ]
