# Generated by Django 3.1.8 on 2021-06-13 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0048_merge_20210413_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_portfolio',
            field=models.ForeignKey(blank=True, help_text='Default Portfolio of the User.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='default_for', to='siteapp.portfolio'),
        ),
    ]
