# Generated by Django 3.2.4 on 2021-07-01 11:43

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0053_auto_20210701_1133'),
        ('siteapp', '0049_user_default_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='import_record',
            field=auto_prefetch.ForeignKey(blank=True, help_text='The Import Record which created this Project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_record_projects', to='controls.importrecord'),
        ),
    ]
