# Generated by Django 3.2.5 on 2021-08-22 03:28

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    # Set name to username by default
    m_model = apps.get_model("siteapp", "user")
    for obj in m_model.objects.all():
        obj.name = obj.username
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0050_project_import_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, blank=True, null=True, unique=True,
                                  help_text="Full name to display.")
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(max_length=200, blank=True, null=True, unique=False,
                                  help_text="Position title.")
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
