# Generated by Django 3.2.5 on 2021-10-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0049_auto_20210423_1555'),
        ('siteapp', '0051_auto_20210822_0328'),
    ]

    operations = [
    ]
