# Generated by Django 3.2.12 on 2022-03-25 22:08

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0052_merge_0049_auto_20210423_1555_0051_auto_20210822_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A UUID (a unique identifier) for this party.')),
                ('party_type', models.CharField(help_text='type for party', max_length=100)),
                ('name', models.CharField(help_text='Name of this party', max_length=250)),
                ('short_name', models.CharField(help_text='Short name of this party', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('role_id', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z_][a-zA-Z0-9_\\-.]*$')])),
                ('title', models.CharField(help_text='Title of role', max_length=250)),
                ('short_name', models.CharField(blank=True, help_text='Short name of this role', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of this role', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
