# Generated by Django 3.2.12 on 2022-03-31 15:19

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0055_auto_20220330_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='party',
            field=auto_prefetch.ForeignKey(blank=True, help_text='The Party appointed to the Role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='siteapp.party'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='role',
            field=auto_prefetch.ForeignKey(blank=True, help_text='The Role being appointed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='siteapp.role'),
        ),
    ]
