# Generated by Django 3.2.12 on 2022-03-31 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0056_auto_20220331_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='party',
            field=models.ForeignKey(help_text='The Party appointed to the Role.', on_delete=django.db.models.deletion.CASCADE, to='siteapp.party'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='role',
            field=models.ForeignKey(help_text='The Role being appointed.', on_delete=django.db.models.deletion.CASCADE, to='siteapp.role'),
        ),
    ]
