# Generated by Django 3.2.12 on 2022-04-18 11:59

import auto_prefetch
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0070_auto_20220418_1140'),
        ('siteapp', '0058_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requested_element',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='controls.element'),
        ),
        migrations.AlterField(
            model_name='request',
            name='system',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='controls.system'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=auto_prefetch.ForeignKey(blank=True, help_text='User creating the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to=settings.AUTH_USER_MODEL),
        ),
    ]
