# Generated by Django 3.2.12 on 2022-04-18 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0070_auto_20220418_1140'),
        ('siteapp', '0059_auto_20220418_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requested_element',
            field=models.ForeignKey(blank=True, help_text='Element being requested.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='controls.element'),
        ),
        migrations.AlterField(
            model_name='request',
            name='system',
            field=models.ForeignKey(blank=True, help_text='System making the request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='controls.system'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User creating the request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL),
        ),
    ]
