# Generated by Django 3.2.13 on 2022-05-16 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0063_auto_20220502_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='req',
            field=models.OneToOneField(blank=True, help_text='Request associated with this proposal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='siteapp.request'),
        ),
    ]
