# Generated by Django 3.2.13 on 2022-06-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0065_alter_proposal_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='project', to='siteapp.Tag'),
        ),
    ]
