# Generated by Django 3.2.14 on 2022-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0078_auto_20220719_1414'),
        ('siteapp', '0067_historicalproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='import_record',
        ),
        migrations.RemoveField(
            model_name='project',
            name='import_record',
        ),
        migrations.AddField(
            model_name='project',
            name='import_record',
            field=models.ManyToManyField(blank=True, help_text='The Import Record which created this Project.', null=True, related_name='import_record_projects', to='controls.ImportRecord'),
        ),
    ]
