# Generated by Django 3.2.14 on 2022-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0079_auto_20220719_1655'),
        ('siteapp', '0068_auto_20220719_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='import_record',
            field=models.ManyToManyField(blank=True, help_text='The Import Record which created this Project.', related_name='import_record_projects', to='controls.ImportRecord'),
        ),
    ]
