# Generated by Django 3.2.16 on 2022-10-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0082_documentid_link_prop_systemtask_timing'),
        ('siteapp', '0070_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibleRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional commentary on the containing object.', null=True)),
                ('links', models.ManyToManyField(blank=True, related_name='responsible_role', to='controls.Link')),
                ('partyUUIDs', models.ManyToManyField(blank=True, related_name='parties', to='siteapp.Party')),
                ('props', models.ManyToManyField(blank=True, related_name='responsible_role', to='controls.Prop')),
                ('roleId', models.ForeignKey(help_text='The Role being appointed.', on_delete=django.db.models.deletion.CASCADE, to='siteapp.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
